Fix TS2339 error in MainLayout
The error TS2339 was caused by attempting to access the `style` property on a generic `Element` type. This commit updates the type of the target element to `HTMLElement` to allow access to the `style` property.